"""AAL anatomical-region overlap for the predicted whole-tumor mask.

Atlas assumptions:
  - `web/data/aal_brats.nii.gz` is the AAL atlas resampled (NN) to the BraTS
    canonical grid (240, 240, 155). Generated by scripts/prepare_webapp_assets.py.
  - `web/data/aal_labels.json` is `{ "1": "Precentral_L", ... }`.

The atlas is loaded once at startup. If a patient upload has a different
spatial shape (non-BraTS-space input) we degrade gracefully by returning
an empty list — the UI shows "Anatomy unavailable for this volume".
"""
from __future__ import annotations

import json
import logging
import os
from typing import Optional

import nibabel as nib
import numpy as np

log = logging.getLogger(__name__)

HERE = os.path.dirname(os.path.abspath(__file__))
ATLAS_PATH = os.path.join(HERE, "data", "aal_brats.nii.gz")
LABELS_PATH = os.path.join(HERE, "data", "aal_labels.json")


class Atlas:
    def __init__(self, data: Optional[np.ndarray], labels: dict[int, str]):
        self.data = data        # None if atlas file is missing
        self.labels = labels

    @property
    def available(self) -> bool:
        return self.data is not None


def load_atlas() -> Atlas:
    if not os.path.exists(ATLAS_PATH):
        log.warning(f"AAL atlas not found at {ATLAS_PATH} — anatomy disabled. "
                    "Run scripts/prepare_webapp_assets.py to generate it.")
        return Atlas(None, {})
    arr = np.asarray(nib.load(ATLAS_PATH).dataobj).astype(np.int32)
    labels = {}
    if os.path.exists(LABELS_PATH):
        with open(LABELS_PATH, "r", encoding="utf-8") as f:
            raw = json.load(f)
        labels = {int(k): str(v) for k, v in raw.items()}
    return Atlas(arr, labels)


def overlap_top_k(labels: np.ndarray, atlas: Atlas, k: int = 5) -> list[dict]:
    """Top-k AAL regions touched by the whole-tumor mask, sorted by % of WT.

    Args:
        labels: (D,H,W) uint8 in {0,1,2,3} predicted labels.
        atlas:  loaded AAL atlas (may be unavailable).
    Returns list of `{"name": str, "label_id": int, "pct": float, "voxels": int}`.
    """
    if not atlas.available:
        return []
    if atlas.data.shape != labels.shape:
        log.info(f"Atlas shape {atlas.data.shape} != input {labels.shape}; "
                 "skipping anatomy.")
        return []

    wt = labels > 0
    wt_count = int(wt.sum())
    if wt_count == 0:
        return []

    atlas_in_wt = atlas.data[wt]
    vals, counts = np.unique(atlas_in_wt, return_counts=True)
    pairs = [(int(v), int(c)) for v, c in zip(vals, counts) if v != 0]
    pairs.sort(key=lambda t: -t[1])

    out = []
    for label_id, n in pairs[:k]:
        out.append({
            "name": atlas.labels.get(label_id, f"label_{label_id}"),
            "label_id": label_id,
            "voxels": n,
            "pct": round(100.0 * n / wt_count, 1),
        })
    return out
